// Augments the project's Env (generated by `wrangler types` into
// worker-configuration.d.ts) with the test-only TEST_MIGRATIONS binding defined
// in vitest.config.mts. Declaration merging means tests see the same
// bindings/vars as the Worker, plus the test scaffolding.
//
// NOTE: keep this file free of top-level import/export so it stays a global
// script — only then does `declare namespace Cloudflare` merge with the
// generated runtime types.
declare namespace Cloudflare {
  interface Env {
    TEST_MIGRATIONS: import("cloudflare:test").D1Migration[];
  }
}

// Vite `?raw` imports (used by test/github-actions.test.ts to read the
// committed deploy.yml without fs access in the workerd test runtime).
declare module "*?raw" {
  const content: string;
  export default content;
}

// `import.meta.glob` — Vite-only API used by the build-size gate
// (test/build-size.test.ts) to read dist/index.js via `?raw` and to skip
// gracefully when `dist/` is absent. Vite's own client types are not wired
// into the test tsconfig, so declare the minimal surface used here.
interface ImportMeta {
  glob<T = unknown>(
    pattern: string,
    options?: { query?: string; import?: string; eager?: boolean },
  ): Record<string, T>;
}

// `node:zlib` is available inside the workerd test runtime, but `@types/node`
// is not installed for a Workers project; declare the one function the
// build-size gate uses (gzipSync of a string or bytes).
declare module "node:zlib" {
  export function gzipSync(data: string | Uint8Array): Uint8Array;
}
