// Augments the project's Env (generated by `wrangler types` into
// worker-configuration.d.ts) with the test-only TEST_MIGRATIONS binding defined
// in vitest.config.mts. Declaration merging means tests see the same
// bindings/vars as the Worker, plus the test scaffolding.
//
// NOTE: keep this file free of top-level import/export so it stays a global
// script — only then does `declare namespace Cloudflare` merge with the
// generated runtime types.
declare namespace Cloudflare {
  interface Env {
    TEST_MIGRATIONS: import("cloudflare:test").D1Migration[];
  }
}

// Vite `?raw` imports (used by test/github-actions.test.ts to read the
// committed deploy.yml without fs access in the workerd test runtime).
declare module "*?raw" {
  const content: string;
  export default content;
}
